# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: luisawork
# "service" is the name of this project. This will also be added to your AWS resource names.
service: middyIntro

provider:
  name: aws
  runtime: nodejs20.x
  architecture: arm64
  region: sa-east-1

package:
  individually: true

build:
  esbuild:
    bundle: true
    minify: true
    sourcemap: true
    external:
      - 'aws-sdk/*'

functions:
  upload:
    handler: src/main/functions/upload.handler
    events:
      - httpApi:
          path: /upload
          method: POST
  users:
    handler: src/main/functions/users.handler
    events:
      - httpApi:
          path: /users
          method: ANY
      - httpApi:
          path: /users/{param+}
          method: ANY

